### ISSUE TITLE
Create Login Page 

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [ajaynegi45/LibraryMan#16]
**Issue: Create Login Page**

**Description:**
The website currently lacks a dedicated login page, essential for user authentication and access to personalized content. This issue aims to initiate the creation of a login page to enhance the user experience and ensure secure access to restricted areas of the site.

**Expected Benefits:**
- Improved user experience with a dedicated and user-friendly login process.
- Enhanced security measures to protect user data.
- Facilitated access to personalized content and features.

**Comment by i-am-SnehaChauhan** [comment]
Please assign this to me.

**Comment by ajaynegi45** [comment]
Hi @i-am-SnehaChauhan ,

Thank you for your interest in this issue. Your input is greatly appreciated.

To address the needs of our users comprehensively, we will create both a Login and Logout page. This approach will ensure that users can securely log in and out as needed, providing a complete and user-friendly experience.

Your contribution to this initiative would be invaluable. Please feel free to start working on these pages or let us know if you have any questions or suggestions along the way.

Let's make the login and logout process as smooth and secure as possible!

**Comment by harshalhonde21** [comment]
Please assign this issue to me. 

I'm a Full Stack Developer and an open source enthusiast with 1.5+ years of expertise in the field.  🚀 I'm eager to contribute to this project and make it dynamic, while also enhancing its security with JWT. 💼

📝 In addition to the technical improvements, I'd like to update both the readme.md and contribution.md files to provide comprehensive documentation for both the backend and frontend sections of the website. 📚

Let's collaborate and take this project to the next level! 🤝💪

**Comment by ajaynegi45** [comment]
> Please assign this issue to me.
> 
> I'm a Full Stack Developer and an open source enthusiast with 1.5+ years of expertise in the field. 🚀 I'm eager to contribute to this project and make it dynamic, while also enhancing its security with JWT. 💼
> 
> 📝 In addition to the technical improvements, I'd like to update both the readme.md and contribution.md files to provide comprehensive documentation for both the backend and frontend sections of the website. 📚
> 
> Let's collaborate and take this project to the next level! 🤝💪

**Assignee:** @harshalhonde21 

Hi @harshalhonde21 ,

Thank you for your enthusiasm and willingness to contribute to our project! We're excited to have you on board.

I'm pleased to inform you that I have assigned the issue to you. You have the freedom to make the website more user-friendly and practical to use, as you mentioned. Your expertise as a Full Stack Developer and your dedication to enhancing both the technical aspects and documentation are highly valued.

If you plan to build the backend of the website, you can use Spring Boot, which is a great choice for creating robust and secure backend services.

Feel free to get started on the improvements, and if you have any questions, need assistance, or would like to discuss specific ideas or requirements, please don't hesitate to reach out. We look forward to collaborating with you and taking this project to the next level!

**Comment by i-am-SnehaChauhan** [comment]
Hey @harshalhonde21 let me do the frontend part u can handle the backend part as u said u are a full-stack Developer. Is it work for you?

**Comment by harshalhonde21** [comment]
@ajaynegi45 thanks for assigning the issue to me.

My expertise in the MERN stack can I do backend with the Express.js and Node.js and for secure login and logout the jwt best choice I will make this project very best.

And what suggestion that when the user login or signup then only the books route should access this feature can I add.

**Comment by harshalhonde21** [comment]
@i-am-SnehaChauhan ya you can but how much time you require to do the frontend part because i am doing the backend part now only and the major part is that fetching the API's and using jwt effecient is very necessary.

**Comment by i-am-SnehaChauhan** [comment]
@harshalhonde21 Thanks, Actually, I am currently in the midst of my midterm exams. If you would like, I can create a basic page, and once I have some free time, I will enhance its design.

**Comment by harshalhonde21** [comment]
@i-am-SnehaChauhan I am creating the frontend part little bit only login of toggle and all as you say its your exam time you just add the good styling to look page attractive at 1.5 hours my whole backend and api intergration in frontend will happen I will raise the PR if @ajaynegi45  like it he will merge it then you should add all styling and what changes you want by raising your PR.

**Comment by Himanshusharma1105** [comment]
Hey!!! Can you please assign this issue to me. I would like to contribute.
