### ISSUE TITLE
Create discussion forum or chat room

### ISSUE THREAD

**Issue by Mansi168** [ajaynegi45/LibraryMan#17]
Hey, i want to add a new feature where users can engage in conversations about the books they've read, ask questions, and share insights via duscussion forum or chat room.

**Comment by ajaynegi45** [comment]
> Hey, i want to add a new feature where users can engage in conversations about the books they've read, ask questions, and share insights via duscussion forum or chat room.

Hi there,

Thank you for suggesting this exciting new feature! It's a great idea to allow users to engage in conversations about the books they've read.

To get started with implementing this feature, we need to discuss the technical details and user experience. Could you please provide more information on how you envision creating the discussion forum or chat room? 

Looking forward to your response! 👀

**Comment by Mansi168** [comment]
hey thanks for assigning this issue!
