### ISSUE TITLE
Migrate base styles to bootstrap

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/LibraryMan#24]
Hi @sameer1612,

I wanted to let you know that I've assigned the "Migrate base styles to bootstrap" issue to you. Your expertise and assistance in tackling this task are greatly appreciated. 

Please feel free to begin working on it at your convenience. If you have any questions or need further clarification regarding the issue, don't hesitate to reach out.

Thank you for your commitment to improving our project's styles and ensuring a smoother user experience.

**Comment by sameer1612** [comment]
we should merge the PR to main and do refactoring on top of it, rather than clubbing all together. that was still a valid issue and accordion fix is isolated from overall style migration.

**Comment by ajaynegi45** [comment]
> we should merge the PR to main and do refactoring on top of it, rather than clubbing all together. that was still a valid issue and accordion fix is isolated from overall style migration.

But that changes are affecting the other part of website. Fix that issues, then create pr i will merge

**Comment by lucasfirmo62** [comment]
Hi @ajaynegi45, is anyone doing this issue? I'd like to do! If no one is doing it, you can put me as Assignees!
