### ISSUE TITLE
Add Accordion

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/LibraryMan#3]
Add Accordion for shlok commentaries

**Comment by ajaynegi45** [comment]
> @ajaynegi45 Ready to work on it. Please assign if it’s up for grabs. Thanks!

**Assignee:** @sameer1612 

Hi @sameer1612 ,

 I'm pleased to inform you that I have assigned this issue to you. Your willingness to contribute to our project is greatly appreciated.

Please feel free to start working on the task, and if you have any questions or need assistance during the process, don't hesitate to reach out. We're looking forward to seeing your contributions to the implementation of the accordion feature for Shlok commentaries.

**Comment by sameer1612** [comment]
<img width="1352" alt="Screenshot 2023-10-05 at 3 21 52 PM" src="https://github.com/ajaynegi45/Library/assets/39580073/0ac5b2a6-3799-4568-bdda-84cbf83e0cc4">


@ajaynegi45  I believe you were referring to these cards with blue headers (clicking on which does nothing as of now). Is the ideal behaviour that,  clicking on the card header will hide the content and clicking again will show it?

Please clarify the expectation so that I can start implementing. Thanks!

**Comment by ajaynegi45** [comment]
> <img alt="Screenshot 2023-10-05 at 3 21 52 PM" width="1352" src="https://user-images.githubusercontent.com/39580073/272861848-0ac5b2a6-3799-4568-bdda-84cbf83e0cc4.png">
> @ajaynegi45 I believe you were referring to these cards with blue headers (clicking on which does nothing as of now). Is the ideal behaviour that, clicking on the card header will hide the content and clicking again will show it?
> 
> Please clarify the expectation so that I can start implementing. Thanks!

**Assignee:** @sameer1612 

Hi @sameer1612 ,

You are absolutely correct in your understanding. The ideal behavior for the accordions is as follows:

- Clicking on the blue header of the accordion should expand and display the commentaries.
- Clicking on the same blue header again should collapse and hide the commentaries.
- Add open and close icon for that

Additionally, please make sure that the accordions are responsive, meaning they should work well on various screen sizes and devices.

At the starting of accordaion and after the chapter and shlok number , include an appropriate title that describes the content. For example, you can use "Commentaries" as the title for accordion. 

Thank you for clarifying, and we appreciate your efforts in implementing this feature. If you have any further questions or need additional information, please feel free to ask.

**Comment by sameer1612** [comment]
@ajaynegi45   please review and merge the pull request for this issue:  https://github.com/ajaynegi45/Library/pull/15

<img width="686" alt="Screenshot 2023-10-05 at 4 50 51 PM" src="https://github.com/ajaynegi45/Library/assets/39580073/34b42d65-a99e-4c1f-9f65-548398c83aaa">
<img width="1436" alt="Screenshot 2023-10-05 at 4 51 00 PM" src="https://github.com/ajaynegi45/Library/assets/39580073/25d0cb8f-15a7-426d-b6be-b0150e15e91a">

**Comment by sameer1612** [comment]
Also, you don't need to write all that css, you installed react bootstrap but did not import the css file for it. We can clean up almost 80% of the css in this project and use ones provided by react bootstrap. If you want me to help with that, do raise a issue and tag me.

**Comment by ajaynegi45** [comment]
I've assigned the issue to you https://github.com/ajaynegi45/Library/issues/24#issue-1929605149
