### ISSUE TITLE
UI and Backend for Login Logout and Profile Section When Login then only the books route will show.

### ISSUE THREAD

**Issue by harshalhonde21** [ajaynegi45/LibraryMan#42]
📚 In the Library application, there's currently only a frontend component with a non-functional login button. 😕

✨ To enhance the application, we need to add a login and signup page. When users login or signup, they should be directed to a profile section where all their details will be displayed. Additionally, there should be a logout button for user convenience. 🚀

🌐 To achieve this, we'll create a robust backend using Express.js and Node.js, implementing JWT (JSON Web Token) for security. We'll also focus on developing an intuitive user interface with appealing UI elements and smooth toggles. 🎨
![opensourcess](https://github.com/ajaynegi45/Library/assets/105191619/9d84c037-339a-45e1-94a2-1ec67255e2d8)

**Comment by harshalhonde21** [comment]
👨‍💻 I'm a Full Stack Developer and an open source enthusiast with 1.5+ years of expertise in the field. 🚀 I've taken the initiative to create the issue, and I'm eager to contribute to this project and make it dynamic, while also enhancing its security with JWT. 💼

📝 In addition to the technical improvements, I'd like to update both the readme.md and contribution.md files to provide comprehensive documentation for both the backend and frontend sections of the website. 📚

Let's collaborate and take this project to the next level! 🤝💪

**Comment by ajaynegi45** [comment]
assigned 👍🏻

**Comment by harshalhonde21** [comment]
Thanks for assigning the issue I am doing the work in 1.5 hours i will raise the PR for you to Merge and reveiew

**Comment by harshalhonde21** [comment]
And can you add the labels of hacktoberfest and all.
It will help to me but my main motive is to contribute in your repo and make the project backend and frontend very best and want make connection with you.

**Comment by ajaynegi45** [comment]
> Thanks for assigning the issue I am doing the work in 1.5 hours i will raise the PR for you to Merge and reveiew

Please take your time to ensure that the work meets our quality standards. Quality matters more than quantity, and we value the effort you put into making the project better.

If you have any questions or need any assistance during the process, feel free to reach out. We look forward to reviewing your pull request when it's ready.


Read This https://github.com/ajaynegi45/Library/issues/27#issue-1929940047

**Comment by harshalhonde21** [comment]
okk @ajaynegi45 your future scope and dedication to Bhagavad Gita inspire me lot I have read your comment and make the mindset that I ready to work with you and make the project like your dream project i just want your support and I am make use of all my skills of MERN stack to inhance your project and make success your project.

**Comment by harshalhonde21** [comment]
I have created the pull request of frontend part of login and logout and userprofile you can check it and one problem is happing with me backend is not push in my fork and I am not able to created the pull request for backend also what can i do now can you tell.

**Comment by harshalhonde21** [comment]
@ajaynegi45  success done with all the changes i had done in backend as well as frontend is succesfully pushed to your repo now its your turn to review it and merge thanks for giving chance to contribute to your project.
