### ISSUE TITLE
Create a bottom to top arrow

### ISSUE THREAD

**Issue by Arnabhit** [ajaynegi45/LibraryMan#46]
A bottomto top arrow is missing. I want to add it . Please assign it to me

**Comment by ajaynegi45** [comment]
Assignee: @Arnabhit 

Hi @Arnabhit ,

Thank you for expressing your interest in working on the "Create a bottom to top arrow" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project and "bottom to top arrow" on Website is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out. We eagerly anticipate your work on creating an visually appealing "bottom to top arrow" for our website.

**Comment by amrahs02** [comment]
Hello @ajaynegi45  , I noticed that the assigned contributor hasn't provided any updates on the issue for a week. Would it be possible to reassign it to me so I can help move it forward?

**Comment by Arnabhit** [comment]
@amrahs02  you can do it

**Comment by ajaynegi45** [comment]
> Assignee: @Arnabhit
> 
> Hi @Arnabhit ,
> 
> Thank you for expressing your interest in working on the "Create a bottom to top arrow" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project and "bottom to top arrow" on Website is much appreciated.
> 
> Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out. We eagerly anticipate your work on creating an visually appealing "bottom to top arrow" for our website.

Assignee: @amrahs02

Hi @amrahs02,

Thank you for expressing your interest in working on the "Create a bottom to top arrow" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project and "bottom to top arrow" on Website is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out. We eagerly anticipate your work on creating an visually appealing "bottom to top arrow" for our website.

**Comment by Himanshusharma1105** [comment]
Hey !!  I would like to contribute to this issue. Can you please assign this issue to me?

**Comment by amrahs02** [comment]
hey @himanshu i am already working on it.
