### ISSUE TITLE
Inhancement in the ui of the footer.

### ISSUE THREAD

**Issue by Aarav238** [ajaynegi45/LibraryMan#57]
The ui of footer is not up to the mark ,   I would like to work on it and make it attractive.
please assign this issue to me . 
@ajaynegi45 
![image](https://github.com/ajaynegi45/Library/assets/95538627/0617c3a1-16d4-46d0-9929-5279da52cdd0)

**Comment by ajaynegi45** [comment]
Assignee: @Aarav238 

Hi @Aarav238,

Thank you for expressing your interest in working on the "Footer" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project and "Footer Design" on Website is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out. We eagerly anticipate your work on creating an informative and visually appealing "Footer" for our website.


Before anything read this https://github.com/ajaynegi45/Library/issues/7#issuecomment-1751998148
