### ISSUE TITLE
Create Sign Up Page

### ISSUE THREAD

**Issue by Krunal-Karena** [ajaynegi45/LibraryMan#58]
Current version of website don't have **sign up page** & also sign up option on navbar.
when user visit first time we need some basic information from user.
Sign Up page is easy way to authenticate user.

**Comment by ajaynegi45** [comment]
> Current version of website don't have **sign up page** & also sign up option on navbar. when user visit first time we need some basic information from user. Sign Up page is easy way to authenticate user.

**Assignee:** @Krunal-Karena 

Hi @Krunal-Karena,

Thank you for taking on this task, and I appreciate your willingness to work on it. Adding a sign-up page and integrating it into the navbar is indeed a valuable addition to our website, providing an easy way to authenticate users.

For this task, we are using Spring Boot for the backend, which offers secure and efficient authentication mechanisms. You can proceed with implementing the sign-up page and integrating it into the navbar using Spring Boot.

If you have any questions, need any assistance, or would like to discuss specific requirements or features for the sign-up page, please feel free to reach out. We look forward to seeing your contributions in enhancing the user experience on our website.
