### ISSUE TITLE
improve navbar

### ISSUE THREAD

**Issue by SumitMangrati** [ajaynegi45/LibraryMan#6]
The menus in the navbar section are disappearing when the size of the screen is reduced.
I can fix this issue by include a toggle menu when the size of the screen is reduced in tablet-view or mobile-view
the toggle menu will toggle when pressed and will contain all the menus of the navbar.
Assign me this task

**Comment by ajaynegi45** [comment]
> The menus in the navbar section are disappearing when the size of the screen is reduced. I can fix this issue by include a toggle menu when the size of the screen is reduced in tablet-view or mobile-view the toggle menu will toggle when pressed and will contain all the menus of the navbar. Assign me this task

**Assignee:** @SumitMangrati

Hi Sumit,

Thank you for volunteering to work on this issue! I've assigned the task to you.

To enhance the user experience further, here are a couple of additional requirements:

1. **Screen Size Responsiveness:** Please ensure that the toggle menu you're implementing activates when the screen size is reduced in tablet and mobile views.

2. **Maximum Navbar Width:** When the screen size increases, let's fix the maximum width of the navbar. This will help maintain a consistent layout on larger screens.

3. **Glass Morphism Effect:** Additionally, I'd like to incorporate a Glass morphism effect into the navbar. This effect provides a sleek and modern look. Please apply the Glass morphism effect to the navbar elements for added visual appeal.

Feel free to reach out if you have any questions or need clarification on any of these requirements. Looking forward to seeing your contributions!

**Comment by SumitMangrati** [comment]
yes i have been working on this , thank you for assigning soon i'll be requesting a PR

**Comment by Raghu1124** [comment]
hello @ajaynegi45 , i would like to work on this issue, please assign it to me

**Comment by SumitMangrati** [comment]
@ajaynegi45 i have submitted a PR, see and review it.

**Comment by ajaynegi45** [comment]
> @ajaynegi45 i have submitted a PR, see and review it.

https://github.com/ajaynegi45/Library/pull/20#pullrequestreview-1661322650

**Comment by ajaynegi45** [comment]
> hello @ajaynegi45 , i would like to work on this issue, please assign it to me

Assignee: @Raghu1124 

Hi @Raghu1124,

Thank you for expressing your interest in working on the "Improve Navbar" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project and "Improve Navbar" on Website is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out. We eagerly anticipate your work on creating an informative and visually appealing "Improve Navbar" for our website.
