### ISSUE TITLE
Redesign Footer

### ISSUE THREAD

**Issue by bhalerao-2002** [ajaynegi45/LibraryMan#7]
Hi @ajaynegi45, 
A footer is an excellent tool for overview introduction, Social handle promotion and ease of navigation for users.
The current footer of your website is very basic, I'd appreciate it if you could give me a chance to enhance it for more user engagement.
Happy Developing :)

Note:- Add the Hacktoberfest, Hacktoberfest-accepted and related labels.

**Comment by ajaynegi45** [comment]
**Assignee:**  @bhalerao-2002 

Hi @bhalerao-2002 

Thank you for your enthusiasm and willingness to enhance our footer! I've assigned the task to you, and we appreciate your dedication to improving the user experience.

Feel free to get started, and if you have any questions or need access to any specific resources, please don't hesitate to reach out. We look forward to seeing your enhancements to the footer.

Additionally, we've added the "Hacktoberfest" and "Hacktoberfest-accepted" labels to this issue, as per your note.

Happy developing, and thank you for your contributions!

**Comment by ajaynegi45** [comment]
@bhalerao-2002  are you currently working on this issue ?

**Comment by bhalerao-2002** [comment]
Hi @ajaynegi45, 
I am out of town for now.  I hade done Layouts, Just issues in position, I had committed you work and will get you done with it. Have some patience.
Happy Developing :) 
Thanks for waiting.

**Comment by Raghu1124** [comment]
Hello! I would like to contribute to this issue, please assign me this issue

**Comment by Sanketmane2323** [comment]
Hey I would like to work on these issue

**Comment by ajaynegi45** [comment]
Hello @Sanketmane2323 and @Raghu1124,

Thank you all for your interest in contributing to this task. I appreciate your willingness to help us on "Redesign Footer" issue.

To make this process more collaborative, I'm assigning this task to all of you. You can each work on your own version. In the end, we will evaluate the contributions and choose the one that best aligns with our project's needs and goals.

Please coordinate among yourselves and feel free to discuss any questions or ideas you may have during the process. Once you've completed your contributions, please submit them for review.

Looking forward to seeing your work and thank you for your valuable contributions! ❤️

**Comment by ajaynegi45** [comment]
Footer design should be like this. Add small description under the name

<img width="1428" alt="Screenshot 2023-10-08 at 4 24 41 PM" src="https://github.com/ajaynegi45/Library/assets/97536703/20a1dcde-34a9-4fc3-a494-2d3d83ac4fdb">
