### ISSUE TITLE
feature: Book read page UI redesign

### ISSUE THREAD

**Issue by imSmaity** [ajaynegi45/LibraryMan#78]
**Description**
Redesign book details read page. A few similar in the below image.

![Books-Web-App-UI-Interaction](https://github.com/ajaynegi45/Library/assets/60940736/b43ccb48-2209-4262-888a-e331fb1a16e9)

**Comment by imSmaity** [comment]
can work that?

**Comment by ajaynegi45** [comment]
> **Description** Redesign book details read page. A few similar in the below image.
> 
> ![Books-Web-App-UI-Interaction](https://private-user-images.githubusercontent.com/60940736/301050746-b43ccb48-2209-4262-888a-e331fb1a16e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODAyMzcsIm5iZiI6MTcwNjY3OTkzNywicGF0aCI6Ii82MDk0MDczNi8zMDEwNTA3NDYtYjQzY2NiNDgtMjIwOS00MjYyLTg4OGEtZTMzMWZiMWExNmU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA1NDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZjc4OGU5MjA4Y2Q2ZDkxMDg0ZmNhYzU0Mzk4YWMwYjJhNmE0MmE3MDVkNzBlMDY3Y2M5ZTU2ZmZjNDRmMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OlMeKwe0UH42qRLsIqW82hMi-qcWAuAmwu1_fS8vnCQ)




@imSmaity 
Yes, you can work on it

**Comment by imSmaity** [comment]
can review that PR @ajaynegi45
