### ISSUE TITLE
Updation of footer by adding icons with social links , adding animations and hover effects.

### ISSUE THREAD

**Issue by Madan2468** [ajaynegi45/LibraryMan#91]
Hey @ajaynegi45 i have also workd with you on upchar aayog repo , so would like to work on it to , so please assign this me under hacktoberfest 2024.

**Comment by ajaynegi45** [comment]
> Hey @ajaynegi45 i have also workd with you on upchar aayog repo , so would like to work on it to , so please assign this me under hacktoberfest 2024.


https://github.com/ajaynegi45/LibraryMan/issues/81
