### ISSUE TITLE
FEATURE: Add Dark Mode Support

### ISSUE THREAD

**Issue by NidhiJain08** [ajaynegi45/LibraryMan#92]
I would like to implement a dark mode feature for this project as part of **GSSoC** and **Hacktoberfest**. It would allow users to switch between light and dark themes, improving the user experience, especially in low-light environments. Please assign this issue to me.

**Comment by ajaynegi45** [comment]
> I would like to implement a dark mode feature for this project as part of **GSSoC** and **Hacktoberfest**. It would allow users to switch between light and dark themes, improving the user experience, especially in low-light environments. Please assign this issue to me.

Hi @NidhiJain08,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project  is much appreciated.
- Copy toggle button from this [project](https://github.com/ajaynegi45/Investment-Calculator)

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by NidhiJain08** [comment]
Hi @ajaynegi45 ,I noticed that the Hacktoberfest label was added to the issue, but the GSSoC label wasn’t assigned. I just wanted to check if there’s anything I need to do from my side to have the GSSoC label added, as I want to contribute through both Hacktoberfest and GSSoC.

Additionally, I was wondering if I could create my own toggle button for the dark mode feature instead of using the one from the project you provided. I believe it would be a great learning experience for me. Thank you for considering my request!

**Comment by ajaynegi45** [comment]
> Hi @ajaynegi45 ,I noticed that the Hacktoberfest label was added to the issue, but the GSSoC label wasn’t assigned. I just wanted to check if there’s anything I need to do from my side to have the GSSoC label added, as I want to contribute through both Hacktoberfest and GSSoC.
> 
> Additionally, I was wondering if I could create my own toggle button for the dark mode feature instead of using the one from the project you provided. I believe it would be a great learning experience for me. Thank you for considering my request!

This project was not part of gssoc. You can create your own.

**Comment by lakshmirajvagu** [comment]
@ajaynegi45 I would like to work on it please assign me

**Comment by Devamani11D** [comment]
@lakshmirajvagu , The issue was already assigned to @NidhiJain08 .
Thank you for expressing your interest in the project. Please feel free to work on other issues and contributions to the project. 🚀 
Thank you.

**Comment by Devamani11D** [comment]
@NidhiJain08 ,
i think you have raised one more issue and PR related to this one and the PR is merged.
So closing this issue.
Thank you 👍
