### ISSUE TITLE
Want to Create a Web App that Opens with Web App Manifest

### ISSUE THREAD

**Issue by JahnavikaGopalbvrith** [ajaynegi45/LibraryMan#98]
making it easier to access, use, and engage with the application.

**Comment by ajaynegi45** [comment]
> making it easier to access, use, and engage with the application.

I could not understand it. Explain problem and solution in depth

**Comment by JahnavikaGopalbvrith** [comment]
Actually I want to add install button for installing website as an app but I tried it is not working.
Sorry for raising this issue

**Comment by ajaynegi45** [comment]
> Actually I want to add install button for installing website as an app. I tried but it is not working. Sorry for raising this issue

You want to say Progressive web apps

**Comment by JahnavikaGopalbvrith** [comment]
yes

**Comment by ajaynegi45** [comment]
> yes

You can try it on https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI

**Comment by JahnavikaGopalbvrith** [comment]
Ok I will try to implement this 
Thank you @ajaynegi45
